# Generated by Django 5.0.7 on 2024-07-30 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
